before:
  hooks:
    - go mod tidy
    - go generate ./...

# builds to be run
builds: []

# archives
archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# release to GitHub
release:
  draft: false

changelog:
  # Will not print any skipped entries
  skip: false
  # Will not sort the entries
  sort: true
  filters:
    exclude:
      - '^docs:'
      - '^test:'