before:
  hooks:
    - go mod tidy
    - go generate ./...

# Eliminar o vaciar la sección de builds
builds: []

# Eliminar o comentar la sección de archives si no se necesita
# archives:
#   - format: binary
#     name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
  draft: false

changelog:
  skip: false
  sort: true
  filters:
    exclude:
      - '^docs:'
      - '^test:'