before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  skip: true

release:
  draft: false

changelog:
  skip: false
  sort: true
  filters:
    exclude:
      - '^docs:'
      - '^test:'
