# Preparación: Limpieza y generación de archivos necesarios
before:
  hooks:
    - go mod tidy
    - go generate ./...

# Omite completamente la sección de builds
builds: []

# No definir archives ya que no se generan binarios
archives: []

# Configuración de lanzamiento: publicación en GitHub
release:
  draft: false

# Configuración de changelog
changelog:
  skip: false
  sort: true
  filters:
    exclude:
      - '^docs:'
      - '^test:'
